/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Lean4Yaml.Types
import Lean4Yaml.YamlSpec

/-!
# YAML Token Types

Explicit token types for the two-pass scanner/parser architecture (Phase 9).

**YAML 1.2.2** defines 205 productions in three layers:
- **Character class** (C, 18 productions): predicates on `Char` — not tokens
- **Lexical/Token** (L, 132 productions): character patterns → tokens
- **Syntactic/Grammar** (S, 54 productions): tokens → AST node

The `YamlToken` type represents the output of the L-layer scanner and the
input to the S-layer grammar parser. See `YAML_PRODUCTIONS.md` §Token–Grammar
Layer Analysis for the full production classification.

## Design Decisions

1. **Reuse `ScalarStyle`** from `Types.lean` rather than defining a new enum.
   The five styles (plain, single-quoted, double-quoted, literal, folded) are
   shared between scanner output and AST.

2. **Resolved scalar content.** The `scalar` token carries fully-resolved text:
   escape sequences expanded, line folding applied, chomp style applied. All of
   productions [41]–[61] (escapes), [69]–[72] (folding), [106]–[132] (scalar
   content rules), and [158]–[175] (block scalar processing) are internal to
   the scanner's scalar tokenization logic.

3. **Virtual tokens.** `blockSequenceStart`, `blockMappingStart`, and `blockEnd`
   have no character representation in the input. They are generated by the
   scanner tracking an indentation stack, analogous to Python's INDENT/DEDENT.

4. **Position tracking.** Each token carries its source position (`YamlPos`)
   for error reporting and proof correspondence.

## References

- libyaml: `yaml_token_type_e` in `yaml.h`
- YAML 1.2.2 §5.3 (indicators), §6.8 (directives), §6.9 (node properties),
  §7.3 (flow scalars), §8.1 (block scalars), §9 (document stream)
-/

namespace Lean4Yaml

/-! ## Token Position -/

/--
A positioned token: token value paired with its source location.

The start position records where the token starts in the input — used for
error messages and for proof correspondence between the scanner and the
original character stream. The optional end position marks the first byte
after the last character consumed by the token (exclusive).
-/
structure Positioned (α : Type) where
  /-- Source position where this token starts -/
  pos : YamlPos
  /-- The token value -/
  val : α
  /-- Source position just after the last character of this token (exclusive).
      Populated by the scanner at every emission site. For virtual tokens
      (`blockEnd`, `blockSequenceStart`, `blockMappingStart`, `placeholder`)
      this equals `pos` (zero-width). -/
  endPos : YamlPos := pos
  deriving Repr, BEq, Inhabited

namespace Positioned

/-- The span from start to end of this token. -/
def span {α : Type} (t : Positioned α) : YamlSpan where
  start := t.pos
  stop := t.endPos

end Positioned

/-! ## YAML Token Type -/

/--
YAML 1.2.2 token types.

Based on the layer analysis of all 205 spec productions.
Follows the libyaml scanner model (`yaml_token_type_e`).

Productions [1]–[40] (character classes) are predicates on `Char`,
not tokens. Productions [41]–[200] (lexical) produce these tokens.
Productions [94], [103]–[105], [133]–[157], [176]–[195], [201]–[205]
(syntactic) compose tokens into the AST.
-/
inductive YamlToken where
  /- Stream boundary markers (implicit — no character representation) -/

  /-- Beginning of input. Always the first token emitted. -/
  | streamStart
  /-- End of input. Always the last token emitted. -/
  | streamEnd

  /-- Reserved slot for potential simple key resolution.
      Pushed by `saveSimpleKey` to pre-allocate space for `.key` and
      optionally `.blockMappingStart`. Overwritten in-place by
      `scanValuePrepare` when the key is confirmed, or filtered out
      by `scan` before returning the final token array.
      Never appears in the output token stream. -/
  | placeholder

  /- Directive tokens (§6.8, productions [82]–[93]) -/

  /-- `%YAML major.minor` version directive. -/
  | versionDirective (major minor : Nat)
  /-- `%TAG !handle! prefix` tag shorthand directive. -/
  | tagDirective (handle tagPrefix : String)

  /- Document markers (§9.1.2, productions [203]–[204]) -/

  /-- `---` document start marker. -/
  | documentStart
  /-- `...` document end marker. -/
  | documentEnd

  /- Block structure tokens (virtual — generated by indentation changes).
     These have NO character representation in the input. The scanner
     generates them by tracking an indentation stack, analogous to
     Python's INDENT/DEDENT tokens. -/

  /-- Indentation increase before `-` (block sequence entry).
      Generated when indentation exceeds the current level and the
      next non-space character is `-`. -/
  | blockSequenceStart
  /-- Indentation increase before a mapping key.
      Generated when indentation exceeds the current level and the
      context indicates a block mapping. -/
  | blockMappingStart
  /-- Indentation decrease back to a previous level.
      Generated for each level popped from the indentation stack. -/
  | blockEnd

  /- Block indicator tokens (§5.3, productions [4]–[6]) -/

  /-- `-` followed by whitespace or break (block sequence entry indicator).
      **YAML 1.2.2**: [4] c-sequence-entry -/
  | blockEntry
  /-- `?` followed by whitespace or break (explicit mapping key indicator).
      **YAML 1.2.2**: [5] c-mapping-key -/
  | key
  /-- `:` followed by whitespace or break (mapping value indicator).
      **YAML 1.2.2**: [6] c-mapping-value -/
  | value

  /- Flow indicator tokens (§5.3, productions [7]–[11]) -/

  /-- `[` flow sequence start.
      **YAML 1.2.2**: [8] c-sequence-start -/
  | flowSequenceStart
  /-- `]` flow sequence end.
      **YAML 1.2.2**: [9] c-sequence-end -/
  | flowSequenceEnd
  /-- `{` flow mapping start.
      **YAML 1.2.2**: [10] c-mapping-start -/
  | flowMappingStart
  /-- `}` flow mapping end.
      **YAML 1.2.2**: [11] c-mapping-end -/
  | flowMappingEnd
  /-- `,` flow entry separator.
      **YAML 1.2.2**: [7] c-collect-entry -/
  | flowEntry

  /- Node property tokens (§6.9, productions [96]–[103]) -/

  /-- `&name` anchor definition.
      **YAML 1.2.2**: [101] c-ns-anchor-property -/
  | anchor (name : String)
  /-- `*name` alias reference.
      **YAML 1.2.2**: [104] c-ns-alias-node -/
  | alias (name : String)
  /-- Tag: `!suffix`, `!!suffix`, `!handle!suffix`, or `!<uri>`.
      **YAML 1.2.2**: [97]–[100] c-ns-tag-property -/
  | tag (handle suffix : String)

  /- Scalar tokens (§7.3, §8.1, productions [107]–[175])
     Content is fully resolved: escapes expanded, lines folded, chomp applied. -/

  /-- Scalar content with its presentation style.
      The `value` is the fully-resolved content string (escapes expanded,
      lines folded per style rules, chomp applied for block scalars).
      The `style` records how it appeared in the source for round-trip. -/
  | scalar (value : String) (style : ScalarStyle)

  /- Comment tokens (§6.6, productions [75]–[79]) -/

  /-- Comment text (excluding the leading `#` and whitespace).
      Preserved for Phase 8 (comment round-trip fidelity). -/
  | comment (text : String)
  deriving Repr, Inhabited, DecidableEq

/-! ## Token–Production Traceability

Link each `YamlToken` constructor to its YAML 1.2.2 production(s).
-/

-- §5.3 Indicator characters
attribute [yaml_spec "5.3" 4 "c-sequence-entry"] YamlToken.blockEntry
attribute [yaml_spec "5.3" 5 "c-mapping-key"] YamlToken.key
attribute [yaml_spec "5.3" 6 "c-mapping-value"] YamlToken.value
attribute [yaml_spec "5.3" 7 "c-collect-entry"] YamlToken.flowEntry
attribute [yaml_spec "5.3" 8 "c-sequence-start"] YamlToken.flowSequenceStart
attribute [yaml_spec "5.3" 9 "c-sequence-end"] YamlToken.flowSequenceEnd
attribute [yaml_spec "5.3" 10 "c-mapping-start"] YamlToken.flowMappingStart
attribute [yaml_spec "5.3" 11 "c-mapping-end"] YamlToken.flowMappingEnd
-- §6.6 Comments
attribute [yaml_spec "6.6" 75 "c-nb-comment-text"] YamlToken.comment
-- §6.8 Directives
attribute [yaml_spec "6.8.1" 86 "ns-yaml-directive"] YamlToken.versionDirective
attribute [yaml_spec "6.8.2" 88 "ns-tag-directive"] YamlToken.tagDirective
-- §6.9 Node properties
attribute [yaml_spec "6.9" 97 "c-ns-tag-property"] YamlToken.tag
attribute [yaml_spec "6.9" 101 "c-ns-anchor-property"] YamlToken.anchor
-- §7.1 Alias nodes
attribute [yaml_spec "7.1" 104 "c-ns-alias-node"] YamlToken.alias
-- §7.3 Scalar styles
attribute [yaml_spec "7.3.1" 109 "c-double-quoted",
           yaml_spec "7.3.2" 120 "c-single-quoted",
           yaml_spec "7.3.3" 131 "ns-plain",
           yaml_spec "8.1.2" 170 "c-l+literal",
           yaml_spec "8.1.3" 174 "c-l+folded"] YamlToken.scalar
-- §9.1.2 Document markers
attribute [yaml_spec "9.1.2" 203 "c-directives-end"] YamlToken.documentStart
attribute [yaml_spec "9.1.2" 204 "c-document-end"] YamlToken.documentEnd

/-! ## Token Classification -/

/--
Whether a token is a virtual token (no character representation in input).

Virtual tokens are generated by the scanner's indentation tracking logic,
not by consuming characters. They delimit block structures.
-/
def YamlToken.isVirtual : YamlToken → Bool
  | .streamStart | .streamEnd => true
  | .blockSequenceStart | .blockMappingStart | .blockEnd => true
  | .placeholder => true
  | _ => false

/--
Whether a token can start a node value.

Used by the grammar parser to determine if a node follows after
node properties (anchor, tag).
-/
def YamlToken.canStartNode : YamlToken → Bool
  | .scalar .. | .alias .. => true
  | .flowSequenceStart | .flowMappingStart => true
  | .blockSequenceStart | .blockMappingStart => true
  | .anchor .. | .tag .. => true  -- node properties precede a node
  | _ => false

/--
Whether a token is a flow indicator.

Used to determine flow/block context boundaries.
-/
def YamlToken.isFlowIndicator : YamlToken → Bool
  | .flowSequenceStart | .flowSequenceEnd => true
  | .flowMappingStart | .flowMappingEnd => true
  | .flowEntry => true
  | _ => false

/-! ## Scanner/Parser Error Type -/

/--
Structured error type for the YAML scanner and grammar parser.

Replaces unstructured `Except String` throughout `Scanner.lean` and
`TokenParser.lean` (P10.6e.2). Each constructor corresponds to a
specific error category, making errors machine-inspectable and
pattern-matchable.

**Scanner errors** (13 sites in `Scanner.lean`): character-level
violations detected during tokenization.

**Parser errors** (5 sites in `TokenParser.lean`): token-level
violations detected during grammar parsing.
-/
inductive ScanError where
  /- Character-level errors (Scanner.lean) -/

  /-- Tab character used as indentation — §6.1 violation.
      `s-indent(n)` [63] requires spaces only. -/
  | tabInIndentation     (line col : Nat)
  /-- Character cannot start any token in the current context. -/
  | unexpectedChar       (c : Char) (line col : Nat)
  /-- Quoted scalar opened but never closed (missing closing `"` or `'`). -/
  | unterminatedScalar   (style : ScalarStyle) (line : Nat)
  /-- Escape sequence `\` at end of input with no following character. -/
  | unterminatedEscape   (line : Nat)
  /-- Backslash followed by an unrecognized escape character. -/
  | unknownEscape        (c : Char) (line : Nat)
  /-- Hex escape (`\x`, `\u`, `\U`) has fewer hex digits than required. -/
  | invalidHexEscape     (expected found : Nat) (line : Nat)
  /-- Hex escape value exceeds Unicode range (> U+10FFFF). -/
  | unicodeOutOfRange    (line : Nat)
  /-- Block scalar header not followed by a newline. -/
  | expectedNewline      (line : Nat)
  /-- Scanner iteration limit reached (defensive guard). -/
  | fuelExhausted        (line col : Nat)
  /-- Trailing content after `%YAML` version — §6.8.1 violation. -/
  | directiveTrailingContent (line col : Nat)
  /-- Duplicate `%YAML` directive in the same document — §6.8.1 violation. -/
  | duplicateYamlDirective (line : Nat)
  /-- `%YAML`/`%TAG` directive after document content without `...` — §6.8 violation. -/
  | directiveAfterContent (line : Nat)
  /-- Directives present but no document follows (`---` required) — §6.8 violation. -/
  | directiveWithoutDocument (line : Nat)
  /-- Document marker (`---`/`...`) at col 0 terminates multi-line quoted scalar — §9.1.2. -/
  | documentMarkerInScalar (style : ScalarStyle) (line : Nat)
  /-- Non-comment content after document-end marker `...` — §9.1.2 violation. -/
  | trailingContentAfterDocEnd (line col : Nat)
  /-- `]` or `}` encountered outside any flow collection — §7.4 violation. -/
  | flowEndOutsideFlow (bracket : Char) (line col : Nat)
  /-- Continuation line of quoted scalar is under-indented — §8.1 violation. -/
  | underIndentedScalar (style : ScalarStyle) (line : Nat)
  /-- Document marker (`---`/`...`) inside flow collection — §5.4 violation. -/
  | documentMarkerInFlow (line : Nat)
  /-- Flow content below block indentation level — §8.1 violation. -/
  | underIndentedFlowContent (line col : Nat)
  /-- C0 control character (not matching `[2] nb-json`) inside quoted scalar — §5.1 violation. -/
  | invalidControlChar (c : Char) (style : ScalarStyle) (line col : Nat)

  /- Grammar-level errors (TokenParser.lean) -/

  /-- Expected a specific token but found something else (or end of input). -/
  | expectedToken        (desc : String) (line : Nat) (got : Option String)
  /-- Recursive nesting depth exceeded `maxDepth` (stack overflow guard). -/
  | nestingDepthExceeded (line : Nat)
  /-- `parseYamlSingle*` called but input contains multiple documents. -/
  | multipleDocuments    (count : Nat)
  /-- Unexpected content after a node where no more tokens are expected.
      E.g., trailing text after a quoted scalar in a block mapping value,
      or content after a flow collection close in block context. -/
  | trailingContent      (line col : Nat)
  /-- Anchor defined twice on the same node — §6.9.2 violation. -/
  | duplicateAnchor      (line : Nat)
  /-- Unexpected content on the `---` document-start line.
      YAML §9.1.1: document start is `---` followed by s-l-comments or content
      on a new line. Content on the same line as `---` without directives
      context is ambiguous. -/
  | contentOnDocumentStartLine (line col : Nat)
  /-- Flow collection opened but never closed (missing `]` or `}`). -/
  | unterminatedFlowCollection (bracket : Char) (line : Nat)
  /-- Comma at an invalid position in a flow collection (leading or duplicate). -/
  | invalidFlowEntry    (line col : Nat)
  /-- Implicit key used as value indicator without preceding key content — §7.4 violation. -/
  | invalidImplicitKey  (line : Nat)
  /-- Bare document (no `---`) after a previous document without `...` — §9.2 [211] violation.
      YAML streams allow bare documents only as the first document or after `...`. -/
  | invalidBareDocument (line col : Nat)
  /-- Tag shorthand handle used without a corresponding `%TAG` directive — §6.8.2.2 violation.
      Named handles (e.g., `!prefix!`) are local to the document and must be declared. -/
  | undeclaredTagHandle (handle : String) (line col : Nat)  /-- Whitespace-only line in block scalar exceeds detected content indent — §8.1.3. -/
  | blockScalarIndentMismatch (line col : Nat)
  /-- Alias `*name` used without a preceding `&name` anchor in this document — §7.1 violation. -/
  | undefinedAlias (name : String) (line col : Nat)
  /-- Value indicator `:` after explicit key `?` at wrong indentation —
      §8.2.2 [197] requires `s-indent(n)` before `:` in
      `l-block-map-explicit-value(n)`. -/
  | misindentedExplicitValue (line col : Nat) (expected : Int)
  /-- Value indicator `:` on same line as `?` with no preceding implicit key —
      §8.2.2 [197]: `l-block-map-explicit-value(n)` has `l-` prefix
      (line-start); `:` as explicit value must be on its own line. -/
  | sameLineExplicitValue (line col : Nat)
  deriving Repr, BEq, Inhabited, DecidableEq

/-- Human-readable error message, separated from error construction.

    This is the **only** place where error messages are formatted as strings.
    All error construction sites use ADT constructors with structured data. -/
def ScanError.toString : ScanError → String
  | .tabInIndentation l c      => s!"tab character in indentation at line {l}, column {c}"
  | .unexpectedChar c l col    => s!"unexpected character '{c}' at line {l}, column {col}"
  | .unterminatedScalar .doubleQuoted l => s!"unterminated double-quoted scalar at line {l}"
  | .unterminatedScalar .singleQuoted l => s!"unterminated single-quoted scalar at line {l}"
  | .unterminatedScalar style l => s!"unterminated {repr style} scalar at line {l}"
  | .unterminatedEscape l      => s!"unterminated escape at line {l}"
  | .unknownEscape c l         => s!"unknown escape '\\{c}' at line {l}"
  | .invalidHexEscape exp fnd l => s!"expected {exp} hex digits in escape at line {l}, found {fnd}"
  | .unicodeOutOfRange l       => s!"unicode escape out of range at line {l}"
  | .expectedNewline l         => s!"expected newline after block scalar header at line {l}"
  | .fuelExhausted l c         => s!"scanner fuel exhausted at line {l}, column {c}"
  | .directiveTrailingContent l c => s!"unexpected content after directive at line {l}, column {c}"
  | .duplicateYamlDirective l   => s!"duplicate %YAML directive at line {l}"
  | .directiveAfterContent l    => s!"directive after document content without document-end marker at line {l}"
  | .directiveWithoutDocument l => s!"directive(s) at line {l} with no following document"
  | .documentMarkerInScalar .doubleQuoted l => s!"document marker inside double-quoted scalar at line {l}"
  | .documentMarkerInScalar .singleQuoted l => s!"document marker inside single-quoted scalar at line {l}"
  | .documentMarkerInScalar style l => s!"document marker inside {repr style} scalar at line {l}"
  | .trailingContentAfterDocEnd l c => s!"unexpected content after document-end marker at line {l}, column {c}"
  | .flowEndOutsideFlow b l c => s!"unexpected '{b}' outside flow collection at line {l}, column {c}"
  | .underIndentedScalar .doubleQuoted l => s!"under-indented continuation line in double-quoted scalar at line {l}"
  | .underIndentedScalar .singleQuoted l => s!"under-indented continuation line in single-quoted scalar at line {l}"
  | .underIndentedScalar style l => s!"under-indented continuation line in {repr style} scalar at line {l}"
  | .documentMarkerInFlow l => s!"document marker (--- or ...) inside flow collection at line {l}"
  | .underIndentedFlowContent l c => s!"flow content under-indented at line {l}, column {c}"
  | .invalidControlChar c .doubleQuoted l col => s!"invalid control character U+{String.ofList (Nat.toDigits 16 c.val.toNat |>.map Char.toUpper)} in double-quoted scalar at line {l}, column {col}"
  | .invalidControlChar c .singleQuoted l col => s!"invalid control character U+{String.ofList (Nat.toDigits 16 c.val.toNat |>.map Char.toUpper)} in single-quoted scalar at line {l}, column {col}"
  | .invalidControlChar c style l col => s!"invalid control character U+{String.ofList (Nat.toDigits 16 c.val.toNat |>.map Char.toUpper)} in {repr style} scalar at line {l}, column {col}"
  | .expectedToken desc l (some got) => s!"expected {desc} at line {l}, got {got}"
  | .expectedToken desc _ none => s!"expected {desc} but reached end of tokens"
  | .nestingDepthExceeded l    => s!"maximum nesting depth exceeded at line {l}"
  | .multipleDocuments n       => s!"expected single document, found {n}"
  | .trailingContent l c       => s!"trailing content at line {l}, column {c}"
  | .duplicateAnchor l         => s!"duplicate anchor on the same node at line {l}"
  | .contentOnDocumentStartLine l c => s!"unexpected content on document-start line at line {l}, column {c}"
  | .unterminatedFlowCollection b l => s!"unterminated flow collection '{b}' at line {l}"
  | .invalidFlowEntry l c      => s!"invalid comma in flow collection at line {l}, column {c}"
  | .invalidImplicitKey l      => s!"invalid implicit key at line {l}"
  | .invalidBareDocument l c   => s!"bare document content at line {l}, column {c} — expected '---' or '...' before new document (§9.2)"
  | .undeclaredTagHandle h l c => s!"undeclared tag handle '{h}' at line {l}, column {c} — use %TAG directive to declare it (§6.8.2.2)"
  | .blockScalarIndentMismatch l c => s!"whitespace-only line exceeds detected block scalar content indent at line {l}, column {c} (§8.1.3)"
  | .undefinedAlias name l c => s!"undefined alias '*{name}' at line {l}, column {c} — no preceding '&{name}' anchor in this document (§7.1)"
  | .misindentedExplicitValue l c exp => s!"value indicator ':' at line {l}, column {c} has wrong indentation — expected column {exp} to match block mapping indent (§8.2.2 [197])"
  | .sameLineExplicitValue l c => s!"value indicator ':' at line {l}, column {c} cannot appear on same line as '?' — explicit value must start on its own line (§8.2.2 [197])"

instance : ToString ScanError := ⟨ScanError.toString⟩

/-! ## Token Stream -/

/--
A stream of positioned YAML tokens.

This is the interface between the scanner (L-layer) and the
grammar parser (S-layer). The scanner produces a `TokenStream`,
and the grammar parser consumes it.
-/
structure TokenStream where
  /-- The array of positioned tokens -/
  tokens : Array (Positioned YamlToken)
  /-- Current read position in the token array -/
  pos : Nat := 0
  deriving Repr, Inhabited

/-- Create a `TokenStream` from an array of positioned tokens. -/
def TokenStream.ofTokens (tokens : Array (Positioned YamlToken)) : TokenStream where
  tokens := tokens
  pos := 0

/-- Check if the stream has more tokens. -/
def TokenStream.hasNext (s : TokenStream) : Bool :=
  s.pos < s.tokens.size

/-- Peek at the current token without consuming it. -/
def TokenStream.peek? (s : TokenStream) : Option (Positioned YamlToken) :=
  if s.pos < s.tokens.size then
    some s.tokens[s.pos]!
  else
    none

/-- Read the next token and advance the stream. -/
def TokenStream.next? (s : TokenStream) : Option (Positioned YamlToken × TokenStream) :=
  if s.pos < s.tokens.size then
    some (s.tokens[s.pos]!, { s with pos := s.pos + 1 })
  else
    none

/-- Get the number of remaining tokens. -/
def TokenStream.remaining (s : TokenStream) : Nat :=
  s.tokens.size - s.pos

/-- Get the source position of the current token (for error reporting). -/
def TokenStream.currentPos (s : TokenStream) : YamlPos :=
  match s.peek? with
  | some t => t.pos
  | none => { offset := 0, line := 0, col := 0 }

end Lean4Yaml
