/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Lean4Yaml.Types

/-!
# YAML Token Types

Explicit token types for the two-pass scanner/parser architecture (Phase 9).

**YAML 1.2.2** defines 205 productions in three layers:
- **Character class** (C, 18 productions): predicates on `Char` — not tokens
- **Lexical/Token** (L, 132 productions): character patterns → tokens
- **Syntactic/Grammar** (S, 54 productions): tokens → AST node

The `YamlToken` type represents the output of the L-layer scanner and the
input to the S-layer grammar parser. See `YAML_PRODUCTIONS.md` §Token–Grammar
Layer Analysis for the full production classification.

## Design Decisions

1. **Reuse `ScalarStyle`** from `Types.lean` rather than defining a new enum.
   The five styles (plain, single-quoted, double-quoted, literal, folded) are
   shared between scanner output and AST.

2. **Resolved scalar content.** The `scalar` token carries fully-resolved text:
   escape sequences expanded, line folding applied, chomp style applied. All of
   productions [41]–[61] (escapes), [69]–[72] (folding), [106]–[132] (scalar
   content rules), and [158]–[175] (block scalar processing) are internal to
   the scanner's scalar tokenization logic.

3. **Virtual tokens.** `blockSequenceStart`, `blockMappingStart`, and `blockEnd`
   have no character representation in the input. They are generated by the
   scanner tracking an indentation stack, analogous to Python's INDENT/DEDENT.

4. **Position tracking.** Each token carries its source position (`YamlPos`)
   for error reporting and proof correspondence.

## References

- libyaml: `yaml_token_type_e` in `yaml.h`
- YAML 1.2.2 §5.3 (indicators), §6.8 (directives), §6.9 (node properties),
  §7.3 (flow scalars), §8.1 (block scalars), §9 (document stream)
-/

namespace Lean4Yaml

/-! ## Token Position -/

/--
A positioned token: token value paired with its source location.

The position records where the token starts in the input — this is
used for error messages and for proof correspondence between the
scanner and the original character stream.
-/
structure Positioned (α : Type) where
  /-- Source position where this token starts -/
  pos : YamlPos
  /-- The token value -/
  val : α
  deriving Repr, BEq, Inhabited

/-! ## YAML Token Type -/

/--
YAML 1.2.2 token types.

Based on the layer analysis of all 205 spec productions.
Follows the libyaml scanner model (`yaml_token_type_e`).

Productions [1]–[40] (character classes) are predicates on `Char`,
not tokens. Productions [41]–[200] (lexical) produce these tokens.
Productions [94], [103]–[105], [133]–[157], [176]–[195], [201]–[205]
(syntactic) compose tokens into the AST.
-/
inductive YamlToken where
  /- Stream boundary markers (implicit — no character representation) -/

  /-- Beginning of input. Always the first token emitted. -/
  | streamStart
  /-- End of input. Always the last token emitted. -/
  | streamEnd

  /- Directive tokens (§6.8, productions [82]–[93]) -/

  /-- `%YAML major.minor` version directive. -/
  | versionDirective (major minor : Nat)
  /-- `%TAG !handle! prefix` tag shorthand directive. -/
  | tagDirective (handle tagPrefix : String)

  /- Document markers (§9.1.2, productions [197]–[198]) -/

  /-- `---` document start marker. -/
  | documentStart
  /-- `...` document end marker. -/
  | documentEnd

  /- Block structure tokens (virtual — generated by indentation changes).
     These have NO character representation in the input. The scanner
     generates them by tracking an indentation stack, analogous to
     Python's INDENT/DEDENT tokens. -/

  /-- Indentation increase before `-` (block sequence entry).
      Generated when indentation exceeds the current level and the
      next non-space character is `-`. -/
  | blockSequenceStart
  /-- Indentation increase before a mapping key.
      Generated when indentation exceeds the current level and the
      context indicates a block mapping. -/
  | blockMappingStart
  /-- Indentation decrease back to a previous level.
      Generated for each level popped from the indentation stack. -/
  | blockEnd

  /- Block indicator tokens (§5.3, productions [4]–[6]) -/

  /-- `-` followed by whitespace or break (block sequence entry indicator).
      **YAML 1.2.2**: [4] c-sequence-entry -/
  | blockEntry
  /-- `?` followed by whitespace or break (explicit mapping key indicator).
      **YAML 1.2.2**: [5] c-mapping-key -/
  | key
  /-- `:` followed by whitespace or break (mapping value indicator).
      **YAML 1.2.2**: [6] c-mapping-value -/
  | value

  /- Flow indicator tokens (§5.3, productions [7]–[11]) -/

  /-- `[` flow sequence start.
      **YAML 1.2.2**: [7] c-sequence-start -/
  | flowSequenceStart
  /-- `]` flow sequence end.
      **YAML 1.2.2**: [8] c-sequence-end -/
  | flowSequenceEnd
  /-- `{` flow mapping start.
      **YAML 1.2.2**: [9] c-mapping-start -/
  | flowMappingStart
  /-- `}` flow mapping end.
      **YAML 1.2.2**: [10] c-mapping-end -/
  | flowMappingEnd
  /-- `,` flow entry separator.
      **YAML 1.2.2**: [11] c-collect-entry -/
  | flowEntry

  /- Node property tokens (§6.9, productions [95]–[102]) -/

  /-- `&name` anchor definition.
      **YAML 1.2.2**: [101] c-ns-anchor-property -/
  | anchor (name : String)
  /-- `*name` alias reference.
      **YAML 1.2.2**: [103] c-ns-alias-node -/
  | alias (name : String)
  /-- Tag: `!suffix`, `!!suffix`, `!handle!suffix`, or `!<uri>`.
      **YAML 1.2.2**: [96]–[100] c-ns-tag-property -/
  | tag (handle suffix : String)

  /- Scalar tokens (§7.3, §8.1, productions [107]–[175])
     Content is fully resolved: escapes expanded, lines folded, chomp applied. -/

  /-- Scalar content with its presentation style.
      The `value` is the fully-resolved content string (escapes expanded,
      lines folded per style rules, chomp applied for block scalars).
      The `style` records how it appeared in the source for round-trip. -/
  | scalar (value : String) (style : ScalarStyle)

  /- Comment tokens (§6.6, productions [74]–[79]) -/

  /-- Comment text (excluding the leading `#` and whitespace).
      Preserved for Phase 8 (comment round-trip fidelity). -/
  | comment (text : String)
  deriving Repr, BEq, Inhabited

/-! ## Token Classification -/

/--
Whether a token is a virtual token (no character representation in input).

Virtual tokens are generated by the scanner's indentation tracking logic,
not by consuming characters. They delimit block structures.
-/
def YamlToken.isVirtual : YamlToken → Bool
  | .streamStart | .streamEnd => true
  | .blockSequenceStart | .blockMappingStart | .blockEnd => true
  | _ => false

/--
Whether a token can start a node value.

Used by the grammar parser to determine if a node follows after
node properties (anchor, tag).
-/
def YamlToken.canStartNode : YamlToken → Bool
  | .scalar .. | .alias .. => true
  | .flowSequenceStart | .flowMappingStart => true
  | .blockSequenceStart | .blockMappingStart => true
  | .anchor .. | .tag .. => true  -- node properties precede a node
  | _ => false

/--
Whether a token is a flow indicator.

Used to determine flow/block context boundaries.
-/
def YamlToken.isFlowIndicator : YamlToken → Bool
  | .flowSequenceStart | .flowSequenceEnd => true
  | .flowMappingStart | .flowMappingEnd => true
  | .flowEntry => true
  | _ => false

/-! ## Token Stream -/

/--
A stream of positioned YAML tokens.

This is the interface between the scanner (L-layer) and the
grammar parser (S-layer). The scanner produces a `TokenStream`,
and the grammar parser consumes it.
-/
structure TokenStream where
  /-- The array of positioned tokens -/
  tokens : Array (Positioned YamlToken)
  /-- Current read position in the token array -/
  pos : Nat := 0
  deriving Repr, Inhabited

/-- Create a `TokenStream` from an array of positioned tokens. -/
def TokenStream.ofTokens (tokens : Array (Positioned YamlToken)) : TokenStream where
  tokens := tokens
  pos := 0

/-- Check if the stream has more tokens. -/
def TokenStream.hasNext (s : TokenStream) : Bool :=
  s.pos < s.tokens.size

/-- Peek at the current token without consuming it. -/
def TokenStream.peek? (s : TokenStream) : Option (Positioned YamlToken) :=
  if s.pos < s.tokens.size then
    some s.tokens[s.pos]!
  else
    none

/-- Read the next token and advance the stream. -/
def TokenStream.next? (s : TokenStream) : Option (Positioned YamlToken × TokenStream) :=
  if s.pos < s.tokens.size then
    some (s.tokens[s.pos]!, { s with pos := s.pos + 1 })
  else
    none

/-- Get the number of remaining tokens. -/
def TokenStream.remaining (s : TokenStream) : Nat :=
  s.tokens.size - s.pos

/-- Get the source position of the current token (for error reporting). -/
def TokenStream.currentPos (s : TokenStream) : YamlPos :=
  match s.peek? with
  | some t => t.pos
  | none => { offset := 0, line := 0, col := 0 }

end Lean4Yaml
