name = "lean4-yaml-verified"
defaultTargets = ["Lean4Yaml"]

[leanOptions]
"autoImplicit" = false

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "main"

[[lean_lib]]
name = "Lean4Yaml"

[[lean_lib]]
name = "Tests.SuiteRunner.Meta"

[[lean_lib]]
name = "Tests.SuiteRunner.HtmlReport"

[[lean_exe]]
name = "tests"
root = "Tests.Main"

[[lean_exe]]
name = "demo"
root = "Demo"

[[lean_exe]]
name = "parsetest"
root = "Tests.ParseTest"

[[lean_exe]]
name = "suiterunner"
root = "Tests.SuiteRunner.Main"

[[lean_exe]]
name = "tryparse"
root = "Tests.TryParse"
