name = "L4YamlDoc"

[leanOptions]
"autoImplicit" = false

[[require]]
name = "verso"
git = "https://github.com/NicolasRouquette/verso.git"
rev = "fix/relative-img-urls"

[[lean_lib]]
name = "Doc.L4YAML"

[[lean_exe]]
name = "l4yaml-doc"
root = "Doc.Main"
supportInterpreter = true
