/-
  L4YAML Documentation — Test Results

  This chapter describes the CI-generated test results.
  The actual test output is captured at CI time and placed
  alongside the Verso HTML output in the `reports/` directory.
-/
import VersoManual

open Verso.Genre Manual

set_option pp.rawOnError true

#doc (Manual) "Test Results" =>
%%%
tag := "test-results"
%%%

{index}[test results]
The L4YAML CI pipeline runs every test suite on each push and
pull request.
This chapter describes the test result categories and
links to the most recent CI-generated reports.

Test results are generated by the `test-coverage.yml` GitHub
Actions workflow and published alongside this documentation
in the `reports/` directory.

The interactive coverage dashboard is available at
[reports/index.html](reports/index.html).

# yaml-test-suite Coverage
%%%
tag := "suite-coverage-results"
%%%

{index}[yaml-test-suite coverage]
The `suiterunner` executable runs all 406 unique test cases
from the official yaml-test-suite and generates interactive
HTML coverage reports with filtering, sorting, and per-stage
breakdown.

Interactive reports:

 * [Full Coverage Report](reports/coverage-all.html) —
   all test cases with filtering and sorting
 * [Verified Tests Detail](reports/verified-tests.html) —
   all internal test suites with per-test results
 * [Production Coverage](reports/production-coverage.html) —
   YAML 1.2.2 productions cross-referenced with `@[yaml_spec]` annotations

Coverage by stage:

 * [Scalar Tests](reports/coverage-scalar.html)
 * [Flow Tests](reports/coverage-flow.html)
 * [Block Tests](reports/coverage-block.html)
 * [Document Tests](reports/coverage-document.html)
 * [Advanced Tests](reports/coverage-advanced.html)
 * [Error Tests](reports/coverage-error.html)

# Lean Test Suites
%%%
tag := "lean-test-results"
%%%

{index}[Lean test results]
The following Lean-native test suites are executed and their
output captured:

:::table +header
*
  * Suite
  * Output File
  * Description
*
  * Unit Tests
  * `unit-tests.txt`
  * Core unit tests for parser internals
*
  * Demo
  * `demo.txt`
  * End-to-end parsing demonstrations
*
  * Explicit Key Tests
  * `explicitkeytests.txt`
  * YAML explicit key (`?`) handling
*
  * Flow Tests
  * `flowtests.txt`
  * Flow collection syntax completeness
*
  * Validation Tests
  * `validationtests.txt`
  * Input validation and error reporting
*
  * Dump Round-Trip
  * `dumproundtrip.txt`
  * Parse → dump → parse cycle verification
*
  * Raw Parse Tests
  * `rawparsetests.txt`
  * Token-to-AST parsing validation
*
  * Spec Examples
  * `specexamples.txt`
  * All 132 YAML 1.2.2 specification examples
*
  * Schema Dump
  * `schemadump.txt`
  * Schema resolution and dump formatting
*
  * Scanner Tests
  * `scannertests.txt`
  * Scanner behavior on targeted inputs
*
  * Scanner Spec Examples
  * `scannerspecexamples.txt`
  * Scanner-level tokens for spec examples
*
  * Adversarial Tests
  * `adversarialtests.txt`
  * Handcrafted adversarial inputs
*
  * Mutation Tests
  * `mutationtests.txt`
  * Systematic input perturbation
*
  * Property Tests
  * `propertytests.txt`
  * Randomized property-based testing
*
  * Production Coverage
  * `productioncoverage.txt`
  * Coverage across production-style inputs
*
  * Limit Tests
  * `limittests.txt`
  * Parser security limit enforcement
:::

# Diagnostic Checks
%%%
tag := "diagnostic-results"
%%%

{index}[diagnostic results]
Diagnostic pipelines produce detailed output for regression
tracking:

:::table +header
*
  * Diagnostic
  * Output File
  * Description
*
  * Flow Regression
  * `flowregressioncheck.txt`
  * Flow parsing edge case regression tracking
*
  * Error Stage
  * `errorstagediag.txt`
  * Error stage diagnostic output
*
  * Scalar Stage
  * `scalarstagediag.txt`
  * Scalar stage diagnostic output
:::

# FFI Test Results
%%%
tag := "ffi-test-results"
%%%

{index}[FFI test results]
The FFI layer is tested through three independent paths:

## Python FFI Tests
%%%
tag := "python-ffi-results"
%%%

Two Python test suites validate the `ctypes`-based bindings:

 * _FFI Integration Tests_ (`Tests/test_python_ffi.py`) —
   tests the C shared library directly from Python
 * _Package Tests_ (`python/tests/`) —
   tests the `l4yaml` Python package API

Results are captured as both text logs and JUnit XML,
with an HTML report generated from the JUnit data.

## Cross-Language Comparison
%%%
tag := "cross-lang-results"
%%%

{index}[cross-language comparison]
The cross-language comparison runs the full yaml-test-suite
through all four backends (Lean, C, Python, Rust) across
five limit presets (`unlimited`, `default`, `strict`,
`permissive`, `safe_tags`).

This verifies that the FFI layer preserves identical parsing
behavior — every backend must produce the same pass/fail/skip
results for every test case under every preset configuration.

Results are available at
[Cross-Language Comparison Report](reports/cross-lang-comparison.html).
