#!/usr/bin/env bash
#
# scripts/refactor-phase-4-schema.sh
#
# Blueprint Initiative 1 — Phase 4 (cluster 3 of 10): Schema/.
# See Blueprint/03-code-organization.md "Proposed Proofs/ reorganization"
# and Blueprint/README.md "Phase 4 — Proofs reorganization".
#
# Moves the four schema-domain proof files that the blueprint lists
# under `Proofs/Schema/` into that subfolder and rewrites every
# `import L4YAML.Proofs.Foo` line in the repo to point at the new path.
#
# Files moved (4):
#   L4YAML/Proofs/SchemaComposition.lean -> L4YAML/Proofs/Schema/SchemaComposition.lean
#   L4YAML/Proofs/SchemaDump.lean        -> L4YAML/Proofs/Schema/SchemaDump.lean
#   L4YAML/Proofs/SchemaResolution.lean  -> L4YAML/Proofs/Schema/SchemaResolution.lean
#   L4YAML/Proofs/TagResolution.lean     -> L4YAML/Proofs/Schema/TagResolution.lean
#
# Inbound references (rewritten by this script's anchored sed):
#   L4YAML.lean                                 (4 imports — one per file)
#   Tests/Guards/Proofs/SchemaComposition.lean  (SchemaComposition)
#   Tests/Guards/Proofs/SchemaDump.lean         (SchemaDump)
#   Tests/Guards/Proofs/SchemaResolution.lean   (SchemaResolution)
#
# Namespaces are NOT touched — same precedent as Phase 1 and the
# Foundation/ and Errors/ clusters: the files continue to declare
# `namespace L4YAML.Proofs.SchemaDump` etc. Only the module path
# (file location + `import` statement) moves.
#
# Safety: `git mv` so history follows; anchored `^import L4YAML.Proofs.X$`
# so bare mentions of the module name (docstrings, qualified references)
# are not corrupted.
#
# Reverse: `git reset --hard HEAD` before staging, or revert the commit
# after.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# --- 1. Create target folder ---------------------------------------------
mkdir -p L4YAML/Proofs/Schema

# --- 2. git mv each file -------------------------------------------------
git mv L4YAML/Proofs/SchemaComposition.lean L4YAML/Proofs/Schema/SchemaComposition.lean
git mv L4YAML/Proofs/SchemaDump.lean        L4YAML/Proofs/Schema/SchemaDump.lean
git mv L4YAML/Proofs/SchemaResolution.lean  L4YAML/Proofs/Schema/SchemaResolution.lean
git mv L4YAML/Proofs/TagResolution.lean     L4YAML/Proofs/Schema/TagResolution.lean

# --- 3. Rewrite imports --------------------------------------------------
# Anchored to `^import L4YAML.Proofs.Foo$` so bare occurrences of the
# module names elsewhere (namespace declarations, qualified references)
# are not touched. Order does not matter — the four patterns are disjoint.
#
# Excluded paths:
#   .lake/           — build artifacts, not source
#   docs/api/        — auto-generated API HTML, regenerated by docgen
#   scripts/refactor-phase-4-schema.sh — this script itself

find . \
  -type f \
  \( -name '*.lean' -o -name '*.py' \) \
  -not -path './.lake/*' \
  -not -path './docs/api/*' \
  -not -path './scripts/refactor-phase-4-schema.sh' \
  -print0 |
xargs -0 sed -i \
  -e 's|^import L4YAML\.Proofs\.SchemaComposition$|import L4YAML.Proofs.Schema.SchemaComposition|' \
  -e 's|^import L4YAML\.Proofs\.SchemaDump$|import L4YAML.Proofs.Schema.SchemaDump|' \
  -e 's|^import L4YAML\.Proofs\.SchemaResolution$|import L4YAML.Proofs.Schema.SchemaResolution|' \
  -e 's|^import L4YAML\.Proofs\.TagResolution$|import L4YAML.Proofs.Schema.TagResolution|'

echo ""
echo "Phase 4 (Schema) refactor complete."
echo ""
echo "Next:"
echo "  1. Review 'git status' — 4 renames + 4 touched importers."
echo "  2. lake build  (must succeed before committing)."
echo "  3. git commit."
