#!/usr/bin/env bash
#
# scripts/refactor-phase-4-foundation.sh
#
# Blueprint Initiative 1 — Phase 4 (cluster 1 of N): Foundation/.
# See Blueprint/03-code-organization.md "Proposed Proofs/ reorganization"
# and Blueprint/README.md "Phase 4 — Proofs reorganization".
#
# Moves the four low-level utility proof files that the blueprint lists
# under `Proofs/Foundation/` into that subfolder and rewrites every
# `import L4YAML.Proofs.Foo` line in the repo to point at the new path.
#
# Files moved (4):
#   L4YAML/Proofs/CharClass.lean        -> L4YAML/Proofs/Foundation/CharClass.lean
#   L4YAML/Proofs/LawfulBEq.lean        -> L4YAML/Proofs/Foundation/LawfulBEq.lean
#   L4YAML/Proofs/StringProperties.lean -> L4YAML/Proofs/Foundation/StringProperties.lean
#   L4YAML/Proofs/ValueAlgebra.lean     -> L4YAML/Proofs/Foundation/ValueAlgebra.lean
#
# Inbound references (rewritten by this script's anchored sed):
#   L4YAML.lean                            (4 imports — one per file)
#   L4YAML/Proofs/ParserAnchorProofs.lean  (ValueAlgebra)
#   L4YAML/Proofs/ParserWfaProofs.lean     (ValueAlgebra)
#   L4YAML/Proofs/ScannerPlainScalar.lean  (StringProperties, CharClass)
#   L4YAML/Proofs/StructureProduction.lean (CharClass)
#
# Namespaces are NOT touched — same precedent as Phase 1: the files
# continue to declare `namespace L4YAML.Proofs.CharClass` etc., and
# `open L4YAML.Proofs.ValueAlgebra` lines in consumers work unchanged.
# Only the module path (file location + `import` statement) moves.
#
# Safety: `git mv` so history follows; anchored `^import L4YAML.Proofs.X$`
# so bare mentions of the module name (docstrings, qualified references
# that don't exist today but might in the future) are not corrupted.
#
# Reverse: `git reset --hard HEAD` before staging, or revert the commit
# after.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# --- 1. Create target folder ---------------------------------------------
mkdir -p L4YAML/Proofs/Foundation

# --- 2. git mv each file -------------------------------------------------
git mv L4YAML/Proofs/CharClass.lean        L4YAML/Proofs/Foundation/CharClass.lean
git mv L4YAML/Proofs/LawfulBEq.lean        L4YAML/Proofs/Foundation/LawfulBEq.lean
git mv L4YAML/Proofs/StringProperties.lean L4YAML/Proofs/Foundation/StringProperties.lean
git mv L4YAML/Proofs/ValueAlgebra.lean     L4YAML/Proofs/Foundation/ValueAlgebra.lean

# --- 3. Rewrite imports --------------------------------------------------
# Anchored to `^import L4YAML.Proofs.Foo$` so bare occurrences of the
# module names elsewhere (namespace declarations, qualified references)
# are not touched. Order does not matter here — the four patterns are
# disjoint.
#
# Excluded paths:
#   .lake/           — build artifacts, not source
#   docs/api/        — auto-generated API HTML, regenerated by docgen
#   scripts/refactor-phase-4-foundation.sh — this script itself

find . \
  -type f \
  \( -name '*.lean' -o -name '*.py' \) \
  -not -path './.lake/*' \
  -not -path './docs/api/*' \
  -not -path './scripts/refactor-phase-4-foundation.sh' \
  -print0 |
xargs -0 sed -i \
  -e 's|^import L4YAML\.Proofs\.CharClass$|import L4YAML.Proofs.Foundation.CharClass|' \
  -e 's|^import L4YAML\.Proofs\.LawfulBEq$|import L4YAML.Proofs.Foundation.LawfulBEq|' \
  -e 's|^import L4YAML\.Proofs\.StringProperties$|import L4YAML.Proofs.Foundation.StringProperties|' \
  -e 's|^import L4YAML\.Proofs\.ValueAlgebra$|import L4YAML.Proofs.Foundation.ValueAlgebra|'

echo ""
echo "Phase 4 (Foundation) refactor complete."
echo ""
echo "Next:"
echo "  1. Review 'git status' — 4 renames + 5 touched importers."
echo "  2. lake build  (must succeed before committing)."
echo "  3. git commit."
