import L4YAML.Proofs.Serialization.SerializationWellFormed

/-!
# Commitment-ordered serialization traces

SerializationWellFormed is intentionally a semantics of committed state,
not a lexical left-to-right scan. This module makes the missing ordering rule
explicit and compositional.

An anchored node contributes its anchor definition only after all semantic
events generated by the node's content. Therefore aliases nested inside that
content cannot see the enclosing anchor, while later sibling nodes can.
-/

namespace L4YAMLSerializationCommitTrace

open L4YAMLSerializationWellFormed

inductive CommitNode where
  | atom
  | alias (name : String)
  | seq (children : List CommitNode)
  | anchored (name : String) (content : CommitNode)
  deriving Repr

mutual
  def nodeEvents : CommitNode → List Event
    | .atom => []
    | .alias name => [.useAlias name]
    | .seq children => nodesEvents children
    | .anchored name content => nodeEvents content ++ [.defineAnchor name]

  def nodesEvents : List CommitNode → List Event
    | [] => []
    | node :: rest => nodeEvents node ++ nodesEvents rest
end

lemma nodeEvents_anchor_commit_last (name : String) (content : CommitNode) :
    nodeEvents (.anchored name content) =
      nodeEvents content ++ [.defineAnchor name] := rfl

lemma nodesEvents_cons (node : CommitNode) (rest : List CommitNode) :
    nodesEvents (node :: rest) = nodeEvents node ++ nodesEvents rest := rfl

lemma enclosing_anchor_self_reference_rejected (name : String) :
    ¬ SerializationWellFormed (nodeEvents (.anchored name (.alias name))) := by
  simp [nodeEvents, SerializationWellFormed, WellFormedFrom, AliasAllowed]

lemma later_sibling_alias_allowed (name : String) :
    SerializationWellFormed
      (nodesEvents [.anchored name .atom, .alias name]) := by
  simp [nodesEvents, nodeEvents, SerializationWellFormed, WellFormedFrom, AliasAllowed]

lemma node_boundary_separator (name : String) :
    checkFrom {} (nodeEvents (.anchored name (.alias name))) ≠
      checkFrom {} (nodesEvents [.anchored name .atom, .alias name]) := by
  simp [nodesEvents, nodeEvents, checkFrom, AliasAllowed]

lemma anchored_then_rest_events
    (name : String) (content : CommitNode) (rest : List CommitNode) :
    nodesEvents (.anchored name content :: rest) =
      nodeEvents content ++ [.defineAnchor name] ++ nodesEvents rest := by
  simp [nodesEvents, nodeEvents, List.append_assoc]

lemma empty_anchor_then_alias (name : String) :
    nodesEvents [.anchored name .atom, .alias name] =
      [.defineAnchor name, .useAlias name] := by
  rfl

end L4YAMLSerializationCommitTrace

#print axioms L4YAMLSerializationCommitTrace.enclosing_anchor_self_reference_rejected
#print axioms L4YAMLSerializationCommitTrace.later_sibling_alias_allowed
#print axioms L4YAMLSerializationCommitTrace.node_boundary_separator
#print axioms L4YAMLSerializationCommitTrace.anchored_then_rest_events
