//! Raw FFI bindings to `liblean4yaml.so`.
//!
//! Auto-generated by `bindgen` from `ffi/lean4yaml.h`.
//! Do not edit — re-run `cargo build` to regenerate.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
